namespace TopRatedApp.Enums
{
    public enum SectionType
    {
        Text,
        Icon,
        //Languages:
        ActionScript,
        C,
        CSharp,
        Cpp,
        Clojure,
        CoffeeScript,
        Css,
        Go,
        Haskell,
        Html,
        Java,
        JavaScript,
        Lua,
        Matlab,
        ObjC,
        Perl,
        Php,
        Python,
        R,
        Ruby,
        Scala,
        Shell,
        Swift,
        Tex,
        TypeScript,
        Viml
    }
}